spring.application.name=CalendarEvent

#spring.datasource.url=jdbc:mysql://localhost:3306/calendar_db
#spring.datasource.username=root
#spring.datasource.password=root

#aws server 
spring.datasource.url=jdbc:mysql://database-1.ct8y28e06n7q.ap-south-1.rds.amazonaws.com:3306/calendar_db
spring.datasource.username=admin
spring.datasource.password=admin12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

allowed.ips=127.0.0.1,192.168.1.100
fetch.aws.ip=true

